schemes:
  solarized_dark: &dark
    # Colors (Gruvbox dark)
    primary:
      # hard contrast: background = '#1d2021'
      background: '#282828'
      # soft contrast: background = '#32302f'
      foreground: '#ebdbb2'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

  solarized_light: &light
    # Colors (Gruvbox light)
    primary:
      # hard contrast: background = '#f9f5d7'
      background: '#fbf1c7'
      # soft contrast: background = '#f2e5bc'
      foreground: '#3c3836'

    # Normal colors
    normal:
      black:   '#fbf1c7'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#7c6f64'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#3c3836'

colors: *light

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Hacker
    # family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Hacker
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Hacker
    # Style can be specified to pick a specific face.
    style: Italic

  # Point size
  size: 14.0

window:
  startup_mode: Fullscreen
  padding:
    x: 4
    y: 4
